const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, PageNumber, LevelFormat
} = require('/sessions/intelligent-blissful-clarke/mnt/aml-book1/AML_Book_Project/node_modules/docx');
const fs = require('fs');

const DARK_NAVY="1A1A2E",MID_BLUE="2C3E6B",LIGHT_GREY="F0F2F8",WHITE="FFFFFF";
const cb=(c="CCCCCC")=>({top:{style:BorderStyle.SINGLE,size:1,color:c},bottom:{style:BorderStyle.SINGLE,size:1,color:c},left:{style:BorderStyle.SINGLE,size:1,color:c},right:{style:BorderStyle.SINGLE,size:1,color:c}});
const s=(t,o={})=>new TextRun({text:t,font:"Arial",size:20,color:"222222",...o});
const sb=(t)=>s(t,{bold:true});
const r=(t)=>new TextRun({text:t,font:"Arial",size:22,color:"222222"});

const numCfg=[
  {reference:"bullets",levels:[{level:0,format:LevelFormat.BULLET,text:"•",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360}}}}]},
];

const body=(t)=>new Paragraph({spacing:{after:160},children:[r(t)]});
const spacer=()=>new Paragraph({spacing:{after:200},children:[r("")]});
const h1=(t)=>new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:360,after:200},children:[new TextRun({text:t,font:"Arial",size:36,bold:true,color:DARK_NAVY})]});
const h2=(t)=>new Paragraph({heading:HeadingLevel.HEADING_2,spacing:{before:280,after:160},children:[new TextRun({text:t,font:"Arial",size:28,bold:true,color:MID_BLUE})]});

// Vocabulary table — full alphabetical list
const vocabTerms = [
  ["Alert","A signal generated by a transaction monitoring system or manual process that warrants further investigation. An alert is not a finding — it is a prompt for review. An alert is distinct from an event (which is broader — any piece of evidence contributing to an investigation) and from an infraction (a vendor-specific intermediate signal that may not yet constitute a formal alert). These terms are not interchangeable without qualification."],
  ["AMLA 2020","Anti-Money Laundering Act 2020 (US). The most significant update to US AML law in two decades, introducing beneficial ownership registration, innovation incentives, and an effectiveness standard for AML programmes."],
  ["AMLD (Anti-Money Laundering Directive)","A series of EU directives (AMLD 1 through AMLD 6) establishing AML standards for member states. AMLD 5 (2018) extended obligations to crypto asset providers; AMLD 6 (2020) expanded predicate offences and criminal liability."],
  ["Analytics Protocols","A control framework ensuring proper alignment of algorithms, data, and business knowledge in the execution of AML analytics. The subject of Book 2 in this series."],
  ["ATL (Above the Line)","Transactions or behaviours above a monitoring threshold that generate an alert. The ATL population is the set of transactions that have been flagged for review. See also: BTL."],
  ["BSA (Bank Secrecy Act)","Bank Secrecy Act (US, 1970). The foundational US AML statute, requiring financial institutions to file Currency Transaction Reports (CTRs) for cash transactions exceeding $10,000, Suspicious Activity Reports (SARs) for suspicious transactions, and to maintain records supporting AML investigations."],
  ["BTL (Below the Line)","Transactions or behaviours below a monitoring threshold that do not generate an alert. The BTL population is unreviewed. Hypergeometric sampling (Chapter 6) is used to estimate the SAR rate within it."],
  ["Case","A collection of information compiled to investigate potentially suspicious behaviour. A case is opened when an alert is escalated from L1 to L2 or L3. It aggregates alerts, customer data, transaction records, and analyst notes."],
  ["CDD (Customer Due Diligence)","The process of verifying a customer's identity, understanding the nature of their business, and assessing their risk profile. CDD is required at onboarding and must be updated periodically. Enhanced Due Diligence (EDD) applies to higher-risk customers."],
  ["CDE / KDE (Critical / Key Data Elements)","Interchangeable terms for the data fields that a scenario or model absolutely requires to function. Different institutions and vendors use different terms — CDE and KDE refer to the same concept: fields whose absence or inaccuracy would directly impair a scenario's ability to fire or an investigator's ability to reach a conclusion. The book uses CDE/KDE to reflect this equivalence. CDE testing is the third step of the DQ validation protocol (Lineage → Reconciliation → CDE Testing → Feedback Loop) and assesses five dimensions: Completeness, Uniqueness, Referential Integrity, Distribution, and Missing Values / Illegal Characters. See Chapter 9, Pillar 3."],
  ["CDSA","Corruption, Drug Trafficking and Other Serious Crimes (Confiscation of Benefits) Act (Singapore). The primary statute criminalising money laundering in Singapore and imposing Suspicious Transaction Report (STR) obligations."],
  ["Controls","Means to manage risks. Controls may be automatic (system-enforced) or manual (process-based). In AML, controls include KYC processes, transaction monitoring systems, SAR filing procedures, and staff training programmes."],
  ["Coverage Assessment","The process of systematically evaluating whether a TM scenario set covers the risks identified in the firm's risk assessment. A coverage assessment maps each regulatory red flag or typology indicator to the scenarios that detect it, identifies gaps, and produces a documented gap analysis with remediation timelines. Coverage assessment is the first stage of the TM lifecycle — it determines what scenarios are needed before they are designed. The benchmark for structuring coverage is the FFIEC BSA/AML Examination Manual red flag list. See Chapter 7."],
  ["CRR (Customer Risk Rating)","A risk score assigned to a customer based on policies, reference data (e.g., nationality, occupation, products held), and transactional behaviour. CRR drives the level of due diligence applied and the peer group to which a customer is assigned for transaction monitoring."],
  ["Data Quality","The fitness of data for the purpose for which it is used. One of the five most imprecisely used terms in AML analytics — 'data quality' is often cited as a problem without specifying which fields are affected, to what degree, and with what operational consequence. The author's DQ framework addresses this through a four-step protocol (Lineage → Reconciliation → CDE Identification and Testing → Feedback Loop) that produces specific, actionable findings rather than a general assessment. The core position: missing or imperfect data is not 'bad' — it tells you something about the data pipeline, the onboarding process, or the customer's behaviour. The validation question is not 'is the data perfect?' but 'does the model account for what the data cannot tell it?' See Chapter 9, Pillar 3, and the CDE/KDE entry."],
  ["Disposition","The conclusion of an alert investigation, recorded with supporting reasons and evidence. The three standard dispositions are L1 (not interesting — close), L2 (interesting — escalate for full investigation), and L3 (SAR-worthy — file a report)."],
  ["EDD (Enhanced Due Diligence)","Additional scrutiny applied to higher-risk customers, including politically exposed persons (PEPs), customers from high-risk jurisdictions, and those with complex ownership structures. EDD involves more intensive source of funds and source of wealth investigations than standard CDD."],
  ["Entity Consolidation","Combining customer and counterparty records that refer to the same underlying entity into a single monitoring profile, so that the full picture of that entity's transactional behaviour is visible before analysis begins. Entity consolidation is a prerequisite for graph-based AML and for any scenario that aggregates behaviour across accounts or products. Without entity consolidation, the monitoring graph contains fragmented or duplicate nodes, distorting network analysis. Entity consolidation (for monitoring) is distinct from Entity Resolution (for investigation) — see that entry. A frontier component of modern AML architecture. See Chapter 10, Section 10.3.3."],
  ["Entity Resolution","Resolving the identity of entities for investigative purposes — determining who a pseudonymous address, account holder, or shell company actually is. Entity resolution is used in case investigation to establish beneficial ownership and connect suspicious activity to a real-world person or organisation. Distinct from Entity Consolidation (which combines records for monitoring) — both are essential to advanced AML analytics but operate at different stages of the detection-to-investigation lifecycle. See also: Entity Consolidation."],
  ["Event","Any piece of evidence potentially valuable for creating or contributing to a case investigation. Events are broader than alerts: a branch observation, a fraud referral, or a customer complaint may all be events that contribute to a case even if they did not generate a TM alert."],
  ["False Negative","A case of genuinely suspicious activity that does not generate a TM alert — because the scenario logic does not capture the pattern, the threshold is set too high, or the customer is assigned to the wrong peer group. False negatives are the silent risk in TM: they are undetectable from within the alert population. BTL sampling (Chapter 6) and coverage assessment (Chapter 7) are the primary tools for estimating and reducing the false negative rate. A scenario optimised exclusively for low false positive rates will typically have a high false negative rate."],
  ["False Positive (correct usage)","An alert caused by code bugs, data errors, or scenario design flaws that does not fit the spirit of the scenario. A system failure, not a legitimate alert. Distinct from a noisy alert (see that entry). The AML industry routinely misuses 'false positive' to describe any alert that investigation finds non-suspicious — this misuse implies the scenario malfunctioned when it did not. Reserving 'false positive' for genuine system failures is analytically and operationally important: the remediation for a false positive (fix the bug or data error) is fundamentally different from the remediation for high noise (retune the threshold or improve segmentation). See Chapters 5, 6, and the Noisy Alert entry."],
  ["FATF (Financial Action Task Force)","The international standard-setting body for AML and counter-terrorist financing (CFT). FATF's 40 Recommendations are the global benchmark for AML frameworks. Countries are assessed against these standards in mutual evaluation reviews; non-compliance can result in placement on the FATF grey or black list."],
  ["FCA (Financial Conduct Authority)","The UK's primary financial services regulator. The FCA supervises AML compliance for most UK financial services firms, including retail banks, and has powers to impose unlimited fines and pursue criminal prosecution."],
  ["FFIEC","Federal Financial Institutions Examination Council (US). The FFIEC publishes the BSA/AML Examination Manual — the definitive reference for how US bank examiners assess AML compliance. Widely referenced internationally."],
  ["FinCEN","Financial Crimes Enforcement Network. A bureau of the US Department of the Treasury that administers and enforces the Bank Secrecy Act, issues AML guidance, and manages the SAR database."],
  ["FRAML","Fraud + AML — the convergence approach that combines fraud detection and AML analytics into a unified function, sharing data, models, and analyst resources. The rationale: fraud and money laundering frequently co-occur (mule accounts are often recruited through fraud schemes; account takeover is used to layer funds), and a single integrated view of the customer reduces duplicate effort and improves detection coverage. Use with care — FRAML can imply a structural merger of two functions with distinct regulatory obligations, governance frameworks, and supervisory relationships. In many jurisdictions, the SAR filing obligation and the fraud reporting obligation remain separate. Integration at the analytics level is well-established best practice; integration at the governance level requires careful regulatory analysis."],
  ["Hypergeometric Sampling","A statistical sampling technique applied to the below-the-line (BTL) population to estimate the rate of suspicious activity that is not being detected by current scenarios. Hypergeometric sampling draws cases without replacement from a finite population, making it appropriate for BTL estimation where the population is known and bounded. Used in Chapter 6 to estimate the SAR rate in the below-the-line population without requiring review of every unalerted record."],
  ["Infraction","A vendor-specific term (used notably in some Actimize implementations) for rule-triggered events that may not yet constitute definitive alerts. Infractions are intermediate signals that may be combined or suppressed before generating a formal alert."],
  ["Integration","The third stage of money laundering. The laundered funds re-enter the legitimate economy, appearing to be legal income. Integration is the hardest stage to detect because by this point the funds may have passed through multiple jurisdictions and financial instruments."],
  ["Isolation Forest","An unsupervised machine learning algorithm used for anomaly detection. It isolates anomalies by randomly partitioning the feature space using decision trees. Anomalous observations require fewer partitions to isolate than normal ones. In AML, Isolation Forest is used to score and rank alerts by suspicion without requiring labelled training data."],
  ["JMLSG","Joint Money Laundering Steering Group. A UK private sector body that publishes AML/CFT guidance for financial services firms. JMLSG guidance is approved by HM Treasury and, while not legally binding, is treated as a near-mandatory standard in regulatory examinations."],
  ["KYC (Know Your Customer)","The process of verifying a customer's identity and understanding the nature of their intended business relationship. KYC is the foundation of Customer Due Diligence (CDD) and is required at onboarding under AML law in all major jurisdictions."],
  ["L1 / L2 / L3 Investigation Levels","Three-tier system for alert and case dispositions. L1: not interesting — alert is closed without escalation. L2: interesting — alert is escalated to a senior analyst or investigator for full case investigation. L3: SAR-worthy — the investigation concludes that suspicious activity has occurred and a SAR or STR must be filed."],
  ["Layering","The second stage of money laundering. Funds are moved through a series of transactions — wire transfers, currency conversions, asset purchases — to obscure their origin. Transaction monitoring is most effective at detecting layering patterns."],
  ["MAS (Monetary Authority of Singapore)","Singapore's central bank and integrated financial regulator. MAS administers AML obligations through Notice 1070 and the Technology Risk Management (TRM) Guidelines."],
  ["MLRs (Money Laundering Regulations)","The Money Laundering, Terrorist Financing and Transfer of Funds (Information on the Payer) Regulations 2017 (as amended). The primary implementing legislation for AML obligations on UK financial institutions, transposing EU AML Directives into UK law."],
  ["Model Risk Management (MRM)","The governance framework for identifying, measuring, monitoring, and controlling risks arising from the use of quantitative models. In AML, MRM applies to all scenario rules, segmentation models, threshold calibration methodologies, and ML triage systems. Key frameworks: SR 26-2 (US), PRA SS1/23 (UK)."],
  ["Model Validation","The independent assessment of whether a model is fit for its intended purpose. Distinct from Model Risk Management (MRM), which is the governance framework within which validation operates: MRM is the structure; validation is the process. Under SR 26-2 (US) and PRA SS1/23 (UK), validation must be conducted independently of the model development team. The five-pillar framework (Model Governance, Model Framework, Data Quality, Model Methodology, Model Documentation) provides the operational structure for AML model validation. See Chapter 9."],
  ["NLP (Natural Language Processing)","A branch of artificial intelligence concerned with the analysis and generation of human language. In AML, NLP is applied to regulatory text parsing (extracting red flags from FFIEC or JMLSG guidance), SAR narrative generation, and automated coverage assessment."],
  ["Peer Groups / Segments","Groups of customers expected to exhibit similar transactional behaviours, used as the basis for risk-based threshold calibration. A customer's peer group determines the monitoring thresholds applied to their account. 'Peer group' and 'segment' are used interchangeably in this book."],
  ["Placement","The first stage of money laundering. The criminal introduces illegal funds into the financial system, typically as cash. This is the riskiest stage for the launderer — cash is conspicuous — and the stage at which banks' cash transaction reporting requirements are most directly targeted."],
  ["POCA (Proceeds of Crime Act 2002)","The UK statute that criminalises money laundering and tipping off. POCA defines money laundering broadly, covering acquisition, use, or possession of criminal property. The tipping off offence (s.333A) — disclosing that a SAR has been or may be filed — carries up to two years imprisonment."],
  ["PRA (Prudential Regulation Authority)","The UK's prudential regulator for banks, building societies, and major investment firms. The PRA published Supervisory Statement SS1/23 (2023), which establishes supervisory expectations for model risk management at UK banks."],
  ["Red Flags","Indicators in customer behaviour or transaction patterns that raise concerns about possible financial crime. Red flags are documented in regulatory guidance (FFIEC manual, JMLSG guidance, FATF typology reports) and form the basis of transaction monitoring scenario design."],
  ["Risk Appetite","An institution's defined tolerance for financial crime risk, including acceptable levels of missed suspicious activity (false negatives). Risk appetite is the governance mechanism by which the institution quantifies what coverage it is prepared to accept — for example, a documented statement that a BTL SAR rate below X% is within acceptable bounds. In a TM analytics context, risk appetite operationalises the balance between coverage and operational capacity: it defines what proportion of suspicious activity the institution accepts may go undetected. Risk appetite thresholds are inputs to BTL sampling analysis (Chapter 6) and model validation criteria (Chapter 9). Risk appetite is a governance decision — set by senior management and documented in policy — not an analytical output. See Chapters 1, 6, and 9."],
  ["Risk Tolerance","An organisation's defined baseline acceptance of financial crime risks — the level of residual risk it is prepared to accept after controls have been applied. Risk tolerance is typically expressed as quantitative limits (e.g., maximum acceptable false negative rate for a given scenario)."],
  ["RPA (Robotic Process Automation)","Software tools that automate repetitive, rule-based tasks. In AML, RPA is applied to data gathering for alert investigations, report generation, and the population of case management systems — reducing analyst administrative burden."],
  ["SAR (Suspicious Activity Report)","A mandated regulatory report filed by a financial institution when it knows, suspects, or has reason to suspect that a transaction involves the proceeds of criminal activity. The US equivalent of a Suspicious Transaction Report (STR). Filing a SAR provides the institution with safe harbour against civil liability for the reported transaction."],
  ["SAR-worthy","A case or alert that meets the threshold for filing a Suspicious Activity Report. The threshold is reasonable suspicion, not certainty — an institution need not be certain that a crime has occurred. A SAR-worthy determination (L3 disposition) must be supported by documented reasoning."],
  ["Scenarios","Computer-implementable rules encoding logic derived from typologies and red flags. A scenario specifies: the typology it targets, the red flags it encodes, the rule logic, the threshold parameters, the lookback window, and the customer scope. See Chapter 4 for the full scenario design methodology."],
  ["Segmentation","The process of grouping customers into peer groups based on shared transactional characteristics, enabling risk-based threshold calibration. Segmentation reduces false positives by ensuring customers are monitored against thresholds appropriate to their behaviour profile. See Chapter 5."],
  ["SR 26-2","Federal Reserve / OCC Supervisory Guidance on Model Risk Management (2026). The current US framework for model governance, validation, and development, superseding the earlier SR 11-7 (2011). Establishes that models must be subject to independent validation, documented governance, and ongoing monitoring. Applies to all quantitative methods used in decision-making, including AML scenarios and ML models."],
  ["STR (Suspicious Transaction Report)","The equivalent of a SAR in Canada and certain other jurisdictions. Filed when a financial institution suspects that a transaction is related to money laundering or terrorist financing."],
  ["TDA (Topological Data Analysis)","A mathematical approach to analysing the shape and structure of complex, high-dimensional datasets using tools from algebraic topology (particularly persistent homology). In AML, TDA can detect structural features in transaction networks — such as ring structures in mule networks — that distance-based clustering methods may miss."],
  ["Three Lines of Defence (3LoD)","The governance model defining the roles and responsibilities of the three primary control functions in a financial institution. 1st Line (Line of Business): owns risk and implements controls in day-to-day operations. 1.5th Line (Operations): a distinctive layer in AML analytics — the alert review, case management, and SAR filing function that sits between the business and the FinCrime Risk function. The 1.5th Line is responsible for executing the TM process: reviewing alerts, making L1/L2/L3 dispositions, and filing SARs. 2nd Line (FinCrime Risk / Model Risk Management): independently validates models, sets policy, oversees the programme, and challenges 1st/1.5th Line decisions. 3rd Line (Internal Audit / Independent Model Review): provides periodic independent assurance over the controls and governance of both the 1st/1.5th Line operations and the 2nd Line validation function. The 'independence' requirements in SR 26-2 (US) and PRA SS1/23 (UK) map directly to this 2nd Line/3rd Line distinction."],
  ["Tipping Off","The criminal offence of disclosing to a customer or third party that a SAR has been or is about to be filed, or that a money laundering investigation is underway. Tipping off is an offence under POCA s.333A in the UK, the Bank Secrecy Act in the US, and equivalent legislation in all major jurisdictions. It carries criminal sanctions including imprisonment."],
  ["Transaction Monitoring (TM)","The process of monitoring transactions for financial crime risk. TM is what the institution does — the ongoing surveillance activity. Distinct from the Transaction Monitoring Framework (TMF) and the Transaction Monitoring System (TMS) — see those entries. TM applies scenario rules and ML models to customer transaction data to identify patterns that may indicate money laundering. See Chapter 3 for the full TM lifecycle."],
  ["Typologies","Broad classifications of financial crime behaviours, describing the general methods used to launder money. Typologies are documented by FATF, FFIEC, JMLSG, and other guidance bodies. Scenario design begins with typology identification and translates typological behaviour patterns into specific, computer-implementable rules."],
  ["UML (Unsupervised Machine Learning)","Machine learning techniques that identify patterns in data without labelled training examples. In AML triage, UML is used to score alerts by anomalousness without requiring a labelled dataset of confirmed SAR and non-SAR cases. Isolation Forest and autoencoders are the most commonly deployed UML approaches in AML. See Chapter 8."],
  ["Noisy Alert","An alert that fits the design intent of the scenario or model — the scenario fired correctly — but investigation determines is non-suspicious. Formerly and incorrectly called a 'false positive' in industry usage. A noisy alert is not a system failure; it is the expected output of a well-designed scenario operating at a threshold that accepts some noise in exchange for adequate coverage. The noisy alert rate is the primary operational efficiency metric for TM. Distinct from a False Positive (correct usage) — see that entry. See Chapters 1, 3, 6."],
  ["Transaction Monitoring Framework (TMF)","The holistic, end-to-end process including all policies, personas, governance structures, data flows, controls, and escalation paths that together constitute an institution's transaction monitoring capability. The TMF is how TM is organised and governed. Distinct from Transaction Monitoring (TM) — the process — and the Transaction Monitoring System (TMS) — the software. When a regulator examines a bank's transaction monitoring, they are examining the TMF in its entirety, not just the TMS. See Chapter 3."],
  ["Transaction Monitoring System (TMS)","The software or technology platform implementing transaction monitoring — whether vendor-built (e.g. NICE Actimize, Quantexa, SymphonyAI) or internally developed. The TMS is one component of the Transaction Monitoring Framework (TMF). It executes scenarios, generates alerts, and may support case management. The TMS is never used to refer to the TM process or the TMF. See Chapter 3."],
  ["Full Coverage","A risk is fully addressed by an existing control. The scenario is deployed, data quality for required CDE/KDEs is confirmed, and calibration has been validated. The risk is considered controlled at this point in time. Coverage state is point-in-time, not permanent. See Chapter 7."],
  ["Partial Coverage","A risk is addressed but gaps remain — for example: a scenario exists but does not cover all variants of the typology; the required CDE/KDE data is incomplete; or the scenario covers the red flag for one customer segment but not another. Partial Coverage requires a documented remediation plan and timeline. See Chapter 7."],
  ["No Coverage","A risk has been identified — through the risk assessment, regulatory red flag lists, or investigator feedback — but no control exists to address it. No Coverage findings represent the institution's most significant regulatory exposure and require immediate escalation to the governance forum. See Chapter 7."],
];

// Build vocabulary table
const vocabTable = () => {
  const headerRow = new TableRow({
    children: [
      new TableCell({ borders: cb("999999"), width: { size: 2800, type: WidthType.DXA }, shading: { fill: DARK_NAVY, type: ShadingType.CLEAR }, margins: { top: 100, bottom: 100, left: 120, right: 120 },
        children: [new Paragraph({ children: [s("Term", { bold: true, color: WHITE })] })] }),
      new TableCell({ borders: cb("999999"), width: { size: 6226, type: WidthType.DXA }, shading: { fill: DARK_NAVY, type: ShadingType.CLEAR }, margins: { top: 100, bottom: 100, left: 120, right: 120 },
        children: [new Paragraph({ children: [s("Definition", { bold: true, color: WHITE })] })] }),
    ]
  });
  const dataRows = vocabTerms.map(([term, def], i) => new TableRow({
    children: [
      new TableCell({ borders: cb("CCCCCC"), width: { size: 2800, type: WidthType.DXA }, shading: { fill: i % 2 === 0 ? "FFFFFF" : LIGHT_GREY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
        children: [new Paragraph({ children: [s(term, { bold: true })] })] }),
      new TableCell({ borders: cb("CCCCCC"), width: { size: 6226, type: WidthType.DXA }, shading: { fill: i % 2 === 0 ? "FFFFFF" : LIGHT_GREY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 },
        children: [new Paragraph({ children: [s(def)] })] }),
    ]
  }));
  return new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [2800, 6226], rows: [headerRow, ...dataRows] });
};

const children = [
  h1("Appendix A: Vocabulary"),
  new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text: "Canonical definitions for all terms used in this book. Terms appear in bold on first use in each chapter. Definitions are authoritative — do not paraphrase or redefine these terms in analytical work.", font: "Arial", size: 22, italics: true, color: "444444" })] }),
  spacer(),
  vocabTable(),
  spacer(),
  spacer(),
  h2("Appendix C: Feature Reference Table — Event Triage ML (~30 Features)"),
  body("The following table provides the standard ~30-feature reference for event triage machine learning models (Chapter 8, Section 8.9). Features are organised into three categories. This table is a starting framework; institutions should validate and adapt based on their product mix, customer population, and deployed scenarios."),
  spacer(),
  new Table({ width: { size: 9026, type: WidthType.DXA }, columnWidths: [2200, 1400, 5426], rows: [
    new TableRow({ children: [
      new TableCell({ borders: cb("999999"), width: { size: 2200, type: WidthType.DXA }, shading: { fill: DARK_NAVY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [s("Feature Name", { bold: true, color: WHITE })] })] }),
      new TableCell({ borders: cb("999999"), width: { size: 1400, type: WidthType.DXA }, shading: { fill: DARK_NAVY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [s("Category", { bold: true, color: WHITE })] })] }),
      new TableCell({ borders: cb("999999"), width: { size: 5426, type: WidthType.DXA }, shading: { fill: DARK_NAVY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [s("Description / Risk Signal", { bold: true, color: WHITE })] })] }),
    ]}),
    ...([
      ["CRR Score", "Reference", "Customer Risk Rating 1–5. Primary risk classifier from KYC/CDD process."],
      ["Risk Category", "Reference", "Band derived from CRR: Low / Medium / High."],
      ["Customer Type", "Reference", "Personal / Business / Correspondent / Other."],
      ["Account Type", "Reference", "Current / Savings / Business / Other."],
      ["Jurisdiction", "Reference", "Country of registration or domicile."],
      ["Industry / SIC Code", "Reference", "Sector classification for business accounts."],
      ["Account Age (months)", "Reference", "Months since account opening — short tenure with high activity is a risk indicator."],
      ["KYC/CDD Status", "Reference", "Current or overdue. Days since last review."],
      ["30-Day Inbound Value", "Activity", "Total value of inbound transactions in past 30 days."],
      ["30-Day Inbound Volume", "Activity", "Count of inbound transactions in past 30 days."],
      ["30-Day Outbound Value", "Activity", "Total value of outbound transactions in past 30 days."],
      ["30-Day Outbound Volume", "Activity", "Count of outbound transactions in past 30 days."],
      ["7-Day Inbound Value", "Activity", "Short-window inbound value — captures rapid accumulation (placement/layering indicator)."],
      ["7-Day Outbound Value", "Activity", "Short-window outbound value — captures rapid dispersal (layering indicator)."],
      ["30-Day Cash Value", "Activity", "Total cash transaction value (in and out combined)."],
      ["30-Day Cash Volume", "Activity", "Count of cash transactions."],
      ["30-Day Wire Value", "Activity", "Total wire transfer value."],
      ["30-Day Wire Volume", "Activity", "Count of wire transfers."],
      ["Unique Counterparties (30-Day)", "Activity", "Number of distinct counterparties — high count with small transactions is a mule indicator."],
      ["Average Transaction Size", "Activity", "Mean transaction value over 30 days."],
      ["Inbound/Outbound Ratio", "Activity", "Ratio of inbound to outbound value — high ratio indicates accumulation without dispersal."],
      ["Sanctions Flag", "Derived", "Binary — any party to the transaction on a sanctions list."],
      ["PEP Flag", "Derived", "Binary — customer or connected party is a Politically Exposed Person."],
      ["Previous Fraud Flag", "Derived", "Binary — customer has had a confirmed fraud incident."],
      ["Previous SAR Flag", "Derived", "Binary — SAR previously filed on this customer. High-risk recurrence indicator."],
      ["High-Risk Jurisdiction Value (30-Day)", "Derived", "Total value of transactions involving high-risk jurisdictions."],
      ["High-Risk Jurisdiction Volume (30-Day)", "Derived", "Count of transactions involving high-risk jurisdictions."],
      ["Round-Amount Count", "Derived", "Number of transactions with amounts rounded to nearest 1,000 — structuring/placement indicator."],
      ["Rapid In-and-Out Ratio", "Derived", "Ratio of outbound value within 48h of inbound — layering indicator."],
      ["Dormancy Flag", "Derived", "Binary — account dormant prior to current activity spike — reactivation for laundering indicator."],
    ].map(([feat, cat, desc], i) => new TableRow({ children: [
      new TableCell({ borders: cb("CCCCCC"), width: { size: 2200, type: WidthType.DXA }, shading: { fill: i % 2 === 0 ? "FFFFFF" : LIGHT_GREY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [s(feat, { bold: true })] })] }),
      new TableCell({ borders: cb("CCCCCC"), width: { size: 1400, type: WidthType.DXA }, shading: { fill: i % 2 === 0 ? "FFFFFF" : LIGHT_GREY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [s(cat)] })] }),
      new TableCell({ borders: cb("CCCCCC"), width: { size: 5426, type: WidthType.DXA }, shading: { fill: i % 2 === 0 ? "FFFFFF" : LIGHT_GREY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [s(desc)] })] }),
    ]})))
  ]}),
  spacer(),
  body("Note: This list requires validation against the integrated exercise dataset before publication. The exact feature names, lookback windows, and definitions should align with the deployed scenarios and the data available in the book's synthetic dataset. Author to review and finalise."),
  spacer(),

  h2("Appendix B: About the Author"),
  body("Haibo Zhang is a former HSBC Senior Vice President and Global Head of Applied Analytics for Financial Crime Threat Mitigation. He established HSBC's US AML Model Validation framework and led global AML and Fraud analytics teams spanning multiple continents."),
  body("He holds a PhD in Computational Biology from Rutgers University / New Jersey Institute of Technology, bringing a rigorous quantitative background to the practical challenges of financial crime analytics. He has direct operational experience with Norkom, Actimize, Mantas, Ayasdi, and Quantexa transaction monitoring and analytics systems."),
  body("Haibo is the founder of Compliance Analytics (compliance-analytics.co.uk), an advisory firm specialising in AML analytics, model validation, and analytics team design. He advises banks, FinTechs, and regulators on building analytics programmes that are both technically rigorous and operationally effective."),
  body("He can be contacted at haibo@compliance-analytics.co.uk."),
  body("This book is the first volume in the AML TM Analytics series. The second volume, AML TM Analytics Protocols, will cover the operational protocol frameworks for analytics programme design, team and persona setup, the DQ validation protocol, segmentation and tuning playbooks, and the maturity model for AML TM programmes."),
];

const doc = new Document({
  numbering: { config: numCfg },
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 36, bold: true, font: "Arial", color: DARK_NAVY }, paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 28, bold: true, font: "Arial", color: MID_BLUE }, paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 1 } },
    ]
  },
  sections: [{
    properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    headers: { default: new Header({ children: [new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: MID_BLUE, space: 4 } }, children: [new TextRun({ text: "Applied AML Analytics  |  Appendix", font: "Arial", size: 18, color: MID_BLUE })] })] }) },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Page ", font: "Arial", size: 18, color: "888888" }), new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 18, color: "888888" })] })] }) },
    children
  }]
});

Packer.toBuffer(doc).then(buf => { fs.writeFileSync('/sessions/intelligent-blissful-clarke/mnt/aml-book1/AML_Book_Project/Book1_Appendix_Vocabulary.docx', buf); console.log('Done: Book1_Appendix_Vocabulary.docx'); });
